### ISSUE TITLE
Submodule update problem

### ISSUE THREAD

**Issue by charlesreid1** [dcppc/uncle-archie#23]
There is a problem with the update submodule hook.

When we merge pull requests into dcppc/internal, it automatically opens pull requests in the dcppc/private-www repository.

The problem is when we merge a series of pull requests into dcppc/internal all at once. It creates a whole bunch of pull reuqests in the dcppc/private-www repository. They all have the same name, too, and no information about the commit they bring up to date or the PR they merge in.

It would be better if we could:
* Use a single PR per submodule, and continually keep it updated. If one doesn't exist, create it, but just take a look first.
* Update the PR title to contain a portion of the new commit hash that's being pointed to

**Comment by charlesreid1** [comment]
closed by #26

**Comment by fp9695253** [comment]
Failing tests - come back to this
