### ISSUE TITLE
Github Actions won't replace Uncle Archie (yet)

### ISSUE THREAD

**Issue by charlesreid1** [dcppc/uncle-archie#42]
Github Actions looks like it is going to help replace a lot of Uncle Archie functionality, which is great: <https://techcrunch.com/2018/10/16/github-launches-actions-its-workflow-automation-tool>

but it won't replace Uncle Archie entirely, at least not yet, at least not for complex pipelines. We'll see how it progresses, it could end up replacing Uncle Archie.

**Comment by charlesreid1** [comment]
Also I just want to point out how utterly dorky this picture is

<img width="917" alt="screen shot 2018-10-22 at 11 40 35" src="https://user-images.githubusercontent.com/368075/47311722-58e36e00-d5ef-11e8-9f66-db918855236a.png">

☝️  paging @ACharbonneau

**Comment by ACharbonneau** [comment]
Amazing. I totes want that hat 🤣

**Comment by charlesreid1** [comment]
Amazon CodeStar _will_ replace Uncle Archie, and the best part is we don't have to wait 6 months for University of California bureaucracy to approve it. We need to start using this.

<https://aws.amazon.com/codestar/features/>
