### ISSUE TITLE
update submodule hook behaving strangely

### ISSUE THREAD

**Issue by charlesreid1** [dcppc/uncle-archie#46]
The update submodule hook is not working correctly when there are multiple updates to the same submodule. The PR title is updated just fine, but there is no commit to update existing pull requests.

Possibly related, here is the output log from one update submodule webhook (I believe this was an attempt to update an existing submodule that failed on the `hub` command line command):

```
$ cat /www/archie.nihdatacommons.us/htdocs/output/private_www_update_submodules_20181119125354
======================
======= STDOUT =======


======================
======= STDERR =======
Error creating pull request: Unprocessable Entity (HTTP 422)
No commits between master and update_submodules_20181119_125359
```

**Comment by fp9695253** [comment]
Addressed by #47

**Comment by charlesreid1** [comment]
and #48

**Comment by charlesreid1** [comment]
tested with dcppc/private-www#241 and functioning properly
